# Build environment
dist: xenial

# We provide our own build tools
language: generic

cache:
  directories:
  - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
# Change dir to arosc main project
- cd arosc

install:
# Build dependencies
- stack --no-terminal --install-ghc build --only-dependencies
- stack exec -- alex --version
- stack exec -- happy --version
- stack build alex happy
- ls ~/.local/bin

script:
# Build the package, its tests, and its docs and run the tests
- stack --no-terminal test --haddock --no-haddock-deps
